implemented file upload capability
mghoneimy/php-graphql-client pull request #53
Opened 2021-03-10 14:32 UTC by JardanDuarte

2021-03-14 03:28 UTC, mghoneimy requested changes
Besides the code level comments I have added, we still need:
1. Unit tests to cover new functionality added
2. A GraphQL API server to be able to test this feature against as an integration test

2021-03-14 03:28 UTC, mghoneimy commented on src/Client.php
> +            }
Please define a new class `File` to be used to pass file data instead of passing them as array fields.

2021-06-07 13:37 UTC, ben221199 commented
> A GraphQL API server to be able to test this feature against as an integration test

Monday.com supports files: https://monday.com/developers/v2#mutations-section-add-file-to-column

2021-11-26 15:34 UTC, gisostallenberg commented on src/Client.php
> +            $request = $request->withBody(Psr7\stream_for(json_encode($bodyArray)));
This couples Guzzle tightly to the client. I think stream discovery should be used here. For example with `php-http/discovery`'s `\Http\Discovery\Psr17FactoryDiscovery`:

```php
\Http\Discovery\Psr17FactoryDiscovery::findStreamFactory()->createStream(\json_encode($bodyArray));
```

2022-05-30 23:50 UTC, NickStallman commented
Lighthouse also supports file uploads. https://lighthouse-php.com/master/digging-deeper/file-uploads.html#handling-file-uploads

It's been awhile since this PR has had any activity. It would be good to get this merged.

2026-04-13 20:35 UTC, closed without merging